### ISSUE TITLE
Incomplete starter code

### ISSUE THREAD

**Issue by ceferisbarov** [Julia-XAI/ExplainableAI.jl#169]
Can you please update the example code to be runnable? It looks like README has been updated several times to match the API changes and the runnable example that once existed has been lost in the process:
```jl
using ExplainableAI

# Load model and input
model = ...                      # load classifier model
input = ...                      # input in batch-dimension-last format

# Run XAI method
analyzer = SmoothGrad(model)
expl = analyze(input, analyzer)  # or: analyzer(input)

# Show heatmap
heatmap(expl)

# Or analyze & show heatmap directly
heatmap(input, analyzer)
```
I think it was easier when the `model` and `input` variables were defined beforehand. I have figured it out now, but it can be a frustrating experience for newcomers.

**Comment by adrhill** [comment]
Sorry for the large delay. The `...` in the example was due to DataAugmentations.jl having issues with inverted height and width dimensions.
I created https://github.com/adrhill/ImageNetDataset.jl for this purpose but (so far) decided against registering it. My PRs to DataAugmentations have since been merged an released, so I'll try to address this very soon.

**Comment by ceferisbarov** [comment]
Thanks!
